### ISSUE TITLE
enum_tools.documentation doesn't work

### ISSUE THREAD

**Issue by brandon-leapyear** [domdfcoding/enum_tools#29]
Trying to use `DocumentedEnum` or `document_enum`, I'm unable to get anything working. It seems like unless `INTERACTIVE` is set to `True`, they don't do anything. And indeed, the tests manually turn this on.

https://github.com/domdfcoding/enum_tools/blob/94b16a633e7c97aaeacfc55d7771d2e358ed6735/tests/test_documented_enum.py#L14

Why is it implemented this way? Running `python setup.py build_sphinx` doesn't set `INTERACTIVE` to true. At the very least, should the line above be included in the documentation on how to use the library?

**Comment by brandon-leapyear** [comment]
@domdfcoding bump?

**Comment by 1kastner** [comment]
@brandon-leapyear I am just a user of the package like you. Please create a proper small example that you believe should work but it does not. Then we can understand your issue better.

For my part, I use the `autoenum` directive (see e.g. `ContainerLength` at https://raw.githubusercontent.com/1kastner/conflowgen/main/docs/api.rst) and `document_enum` (see e.g. `ContainerLength` at https://github.com/1kastner/conflowgen/blob/main/conflowgen/domain_models/data_types/container_length.py) together and things work nicely for me. It is a slightly larger project so maybe it is not the easiest example to follow. If your issue lies elsewhere, please elaborate.

Please also notice that `python setup.py build_sphinx` [is deprecated](https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html) so that you should not use it anyway.

**Comment by brandon-leapyear** [comment]
I see. It might just be the `build_sphinx` workflow in particular. It works now, in our new workflow using `sphinx-build`. I'm having some other issues, but I'll break those out into separate issues. Thanks!

**Comment by 1kastner** [comment]
The first part is great to hear and let's hope the small issues can quickly be solved.

**Comment by Gallaecio** [comment]
Seems to fail if `tox` is used to call `sphinx-build`.
